/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import avs.AVS;
import avs.GlobalConstants;
import avs.HelperClass;
import avs.Users;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaymezing
 */
public class SuperuserUI extends javax.swing.JFrame {

    /**
     * Creates new form SuperuserUI
     */
    private static Map<Integer, Users> users;
    private DefaultTableModel table1;
    private DefaultTableModel table2;
    private int selected, selectedID;
    private Users selectedUser;
    public SuperuserUI() {
        initComponents();
        AVS.populate();
        HelperClass.setHelperClass();
        users = AVS.getUsers();
        typeLabel.setVisible(false);
        typeCombo.setVisible(false);

        populateTables();
    }
    
    public SuperuserUI(String x){
        initComponents();
        
    }
    
    private void clean(){
        fnameField.setText("");
        lnameField.setText("");
        unameField.setText("");
        passwordField.setText("");
    }
    
    private void populateTables(){
        //officer table
        table1 = (DefaultTableModel) officerTable.getModel();
        table1.setRowCount(0);
     //   ArrayList<Users> beans =  new ArrayList<Users>(users.values());
        
        
        for( Map.Entry<Integer, Users> entry : users.entrySet()){
            Users u = entry.getValue();
            if(u.getType().equals(GlobalConstants.VOTER)){
                table1.addRow(new Object[]{
                u.getID(), u.getFirst_name() + " " + u.getLast_name()
                
                });
            }
            
        }
        
        //voter table
        table2 = (DefaultTableModel) voterTable.getModel();
        table2.setRowCount(0);
        
        for( Map.Entry<Integer, Users> entry : users.entrySet()){
            Users u = entry.getValue();
            if(u.getType().equals(GlobalConstants.OFFICER)){
                table2.addRow(new Object[]{
                u.getID(), u.getFirst_name() + " " + u.getLast_name()
                
                });
            }
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        officerTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        voterTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userInfoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        unameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        addUserBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Superuser");

        jLabel1.setText("WELCOME SUPERUSER");

        officerTable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        officerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        officerTable.setColumnSelectionAllowed(true);
        officerTable.getTableHeader().setReorderingAllowed(false);
        officerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(officerTable);
        officerTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (officerTable.getColumnModel().getColumnCount() > 0) {
            officerTable.getColumnModel().getColumn(0).setMinWidth(40);
            officerTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            officerTable.getColumnModel().getColumn(0).setMaxWidth(40);
            officerTable.getColumnModel().getColumn(1).setResizable(false);
            officerTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        voterTable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        voterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        voterTable.getTableHeader().setReorderingAllowed(false);
        voterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voterTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(voterTable);
        voterTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (voterTable.getColumnModel().getColumnCount() > 0) {
            voterTable.getColumnModel().getColumn(0).setMinWidth(40);
            voterTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            voterTable.getColumnModel().getColumn(0).setMaxWidth(40);
            voterTable.getColumnModel().getColumn(1).setResizable(false);
            voterTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("VOTERS");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("OFFICERS");

        userInfoPanel.setBackground(new java.awt.Color(153, 255, 255));

        jLabel4.setText("First Name");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel9.setText("Last Name");

        typeLabel.setText("Type");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Officer", "Voter" }));

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(unameField)
                    .addComponent(lnameField)
                    .addComponent(fnameField)
                    .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(unameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        addUserBtn.setText("ADD A NEW USER");
        addUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserBtnMouseClicked(evt);
            }
        });
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(userInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(addUserBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(removeBtn)
                                        .addGap(26, 26, 26)
                                        .addComponent(updateBtn)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addUserBtn)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(removeBtn)
                    .addComponent(updateBtn))
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void officerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officerTableMouseClicked
        // TODO add your handling code here:
        typeLabel.setVisible(false);
        typeCombo.setVisible(false);
        removeBtn.setVisible(true);
        updateBtn.setVisible(true);
         addUserBtn.setVisible(true);
        selected = officerTable.rowAtPoint(evt.getPoint());
        
        if(selected > -1){
            
            selectedID = (int) table1.getValueAt(selected, 0);
            
            System.out.print("Selected id - "+selectedID);
            clean();
            selectedUser = users.get(selectedID);
            fnameField.setText( selectedUser.getFirst_name());
            lnameField.setText( selectedUser.getLast_name());
            unameField.setText( selectedUser.getUsername());
            passwordField.setText( selectedUser.getPassword());
        }
    }//GEN-LAST:event_officerTableMouseClicked

    private void voterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voterTableMouseClicked
        // TODO add your handling code here:

        typeLabel.setVisible(false);
        typeCombo.setVisible(false);
        removeBtn.setVisible(true);
        updateBtn.setVisible(true);
        addUserBtn.setVisible(true);
         selected = officerTable.rowAtPoint(evt.getPoint());

        if(selected > -1){

            selectedID = (int) table2.getValueAt(selected, 0);
            System.out.print("Selected id - "+selectedID);
            clean();
             selectedUser = users.get(selectedID);
            fnameField.setText( selectedUser.getFirst_name());
            lnameField.setText( selectedUser.getLast_name());
            unameField.setText( selectedUser.getUsername());
            passwordField.setText( selectedUser.getPassword());
        }

    }//GEN-LAST:event_voterTableMouseClicked

    private void addUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBtnMouseClicked
        // TODO add your handling code here:
        clean();
        typeLabel.setVisible(true);
        typeCombo.setVisible(true);
        removeBtn.setVisible(false);
        updateBtn.setVisible(false);
        addUserBtn.setVisible(false);
        
    }//GEN-LAST:event_addUserBtnMouseClicked

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
        if(HelperClass.confirmBox("Are you sure you want to delete selected user?")
                == JOptionPane.YES_OPTION ){
            HelperClass.removeOfficer(selectedUser);
            HelperClass.infoBox("Removed user!", "Announcement");
             populateTables();
             clean();
        }
        
    }//GEN-LAST:event_removeBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here
        
        if(!fnameField.getText().equals("") && !lnameField.getText().equals("") &&
                !unameField.getText().equals("") && !passwordField.getText().equals("")){
            String fname = fnameField.getText();
            String lname = lnameField.getText();
            String uname = unameField.getText();
            String pword = passwordField.getText();
             String type = typeCombo.getSelectedItem().toString();
            Users u = new Users(fname, lname, uname, pword,
            type, GlobalConstants.SUPERUSER, selectedID);
            if(HelperClass.confirmBox("Are you sure you want to update selected user?")
                == JOptionPane.YES_OPTION ){
                
                HelperClass.updateOfficer(u);
                HelperClass.infoBox("Updated user!", "Announcement");
                populateTables();
                clean();
            }
        }
        
    }//GEN-LAST:event_updateBtnMouseClicked

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String type = typeCombo.getSelectedItem().toString();
        if(!fnameField.getText().equals("") && !lnameField.getText().equals("") &&
                !unameField.getText().equals("") && !passwordField.getText().equals("")){
            String fname = fnameField.getText();
            String lname = lnameField.getText();
            String uname = unameField.getText();
            String pword = passwordField.getText();
            Users u = new Users(fname, lname, uname, pword,
            type, GlobalConstants.SUPERUSER);
            if(HelperClass.confirmBox("Are you sure you want to add user?")
                == JOptionPane.YES_OPTION ){
                
                HelperClass.addOfficer(u);
                 HelperClass.infoBox("Added new user!", "Announcement");
                 populateTables();
                 clean();
            }
           
        }else{
            HelperClass.infoBox("Missing fields.", "Error");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperuserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperuserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperuserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperuserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperuserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTable officerTable;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton removeBtn;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField unameField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JTable voterTable;
    // End of variables declaration//GEN-END:variables
}
