/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import static avs.AVS.*;
/**
 *
 * @author Sarausad
 */
public class voter_landing_page2 extends javax.swing.JFrame {

    /**
     * Creates new form voter_landing_page2
     */
    public voter_landing_page2() {
        initComponents();
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        governor = new javax.swing.ButtonGroup();
        mayor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        voteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 93, 95));
        jPanel1.setMinimumSize(new java.awt.Dimension(593, 494));
        jPanel1.setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(229, 93, 95));
        governor.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(50, 60, 93, 23);

        jRadioButton2.setBackground(new java.awt.Color(229, 93, 95));
        governor.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("jRadioButton2");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 60, 93, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Governor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 30);

        jRadioButton3.setBackground(new java.awt.Color(229, 93, 95));
        governor.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton3");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(390, 60, 93, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mayor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 240, 30);

        jRadioButton4.setBackground(new java.awt.Color(229, 93, 95));
        mayor.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("jRadioButton1");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(50, 160, 170, 23);

        jRadioButton5.setBackground(new java.awt.Color(229, 93, 95));
        mayor.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("jRadioButton2");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(220, 160, 170, 23);

        jRadioButton6.setBackground(new java.awt.Color(229, 93, 95));
        mayor.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("jRadioButton3");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(390, 160, 170, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("party_name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 80, 80, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("party_name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 80, 80, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("party_name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 80, 80, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("party_name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 180, 150, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("party_name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 180, 150, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("party_name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 180, 150, 14);

        jSeparator1.setForeground(new java.awt.Color(229, 93, 95));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 108, 550, 10);

        jSeparator2.setForeground(new java.awt.Color(229, 93, 95));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 210, 550, 10);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("District Representatives");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(20, 230, 400, 30);

        jCheckBox11.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("jCheckBox1");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox11);
        jCheckBox11.setBounds(50, 280, 130, 23);

        jCheckBox12.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("jCheckBox2");
        jPanel1.add(jCheckBox12);
        jCheckBox12.setBounds(180, 280, 130, 23);

        jCheckBox13.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("jCheckBox3");
        jPanel1.add(jCheckBox13);
        jCheckBox13.setBounds(310, 280, 130, 23);

        jCheckBox14.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setText("jCheckBox4");
        jPanel1.add(jCheckBox14);
        jCheckBox14.setBounds(440, 280, 130, 23);

        jCheckBox15.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setText("jCheckBox5");
        jPanel1.add(jCheckBox15);
        jCheckBox15.setBounds(50, 330, 130, 23);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("party_name");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(70, 300, 110, 14);

        jCheckBox16.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setText("jCheckBox1");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox16);
        jCheckBox16.setBounds(180, 330, 130, 23);

        jCheckBox17.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox17.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setText("jCheckBox2");
        jPanel1.add(jCheckBox17);
        jCheckBox17.setBounds(310, 330, 130, 23);

        jCheckBox18.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox18.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setText("jCheckBox3");
        jPanel1.add(jCheckBox18);
        jCheckBox18.setBounds(440, 330, 130, 23);

        jCheckBox19.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox19.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setText("jCheckBox4");
        jPanel1.add(jCheckBox19);
        jCheckBox19.setBounds(50, 380, 130, 23);

        jCheckBox20.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox20.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setText("jCheckBox5");
        jPanel1.add(jCheckBox20);
        jCheckBox20.setBounds(180, 380, 130, 23);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("party_name");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(200, 300, 110, 14);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("party_name");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(330, 300, 110, 14);

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("party_name");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(460, 300, 110, 14);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("party_name");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(70, 350, 110, 14);

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("party_name");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(200, 350, 110, 14);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("party_name");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(330, 350, 110, 14);

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("party_name");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(460, 350, 110, 14);

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("party_name");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(70, 400, 110, 14);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("party_name");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(200, 400, 110, 14);

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(390, 410, 70, 40);

        voteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        voteButton.setForeground(new java.awt.Color(255, 255, 255));
        voteButton.setText("Vote");
        voteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        voteButton.setContentAreaFilled(false);
        voteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voteButton);
        voteButton.setBounds(480, 410, 70, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new voter_landing_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void voteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voteButtonActionPerformed

    void populateFields(){
        // governor
            jRadioButton1.setText(p23.getLast_name()+", "+p23.getFirst_name());
            jLabel3.setText(p23.getParty());
            jRadioButton2.setText(p24.getLast_name()+", "+p24.getFirst_name());
            jLabel4.setText(p24.getParty());
            jRadioButton3.setText(p25.getLast_name()+", "+p25.getFirst_name());
            jLabel5.setText(p25.getParty());
            
        // mayor
            jRadioButton4.setText(p26.getLast_name()+", "+p26.getFirst_name());
            jLabel6.setText(p26.getParty());
            jRadioButton5.setText(p27.getLast_name()+", "+p27.getFirst_name());
            jLabel7.setText(p27.getParty());
            jRadioButton6.setText(p28.getLast_name()+", "+p28.getFirst_name());
            jLabel8.setText(p28.getParty());
            
        // district representative
            jCheckBox11.setText(p29.getLast_name()+", "+p29.getFirst_name());
            jLabel24.setText(p29.getParty());
            jCheckBox12.setText(p30.getLast_name()+", "+p30.getFirst_name());
            jLabel25.setText(p30.getParty());
            jCheckBox13.setText(p31.getLast_name()+", "+p31.getFirst_name());
            jLabel26.setText(p31.getParty());
            jCheckBox14.setText(p32.getLast_name()+", "+p32.getFirst_name());
            jLabel27.setText(p32.getParty());
            jCheckBox15.setText(p33.getLast_name()+", "+p33.getFirst_name());
            jLabel28.setText(p33.getParty());
            jCheckBox16.setText(p34.getLast_name()+", "+p34.getFirst_name());
            jLabel29.setText(p34.getParty());
            jCheckBox17.setText(p35.getLast_name()+", "+p35.getFirst_name());
            jLabel30.setText(p35.getParty());
            jCheckBox18.setText(p36.getLast_name()+", "+p36.getFirst_name());
            jLabel31.setText(p36.getParty());
            jCheckBox19.setText(p37.getLast_name()+", "+p37.getFirst_name());
            jLabel32.setText(p37.getParty());
            jCheckBox20.setText(p38.getLast_name()+", "+p38.getFirst_name());
            jLabel33.setText(p38.getParty());         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voter_landing_page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup governor;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup mayor;
    private javax.swing.JButton voteButton;
    // End of variables declaration//GEN-END:variables
}
