/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import static avs.AVS.*;

/**
 *
 * @author student
 */
public class voter_landing_page extends javax.swing.JFrame {

    /**
     * Creates new form voter_landing_page
     */
    public voter_landing_page() {
        initComponents();
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presidents = new javax.swing.ButtonGroup();
        vicepresidents = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(569, 572));

        jPanel1.setBackground(new java.awt.Color(229, 93, 95));
        jPanel1.setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(229, 93, 95));
        presidents.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(50, 60, 150, 23);

        jRadioButton2.setBackground(new java.awt.Color(229, 93, 95));
        presidents.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("jRadioButton2");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 60, 170, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("President");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 30);

        jRadioButton3.setBackground(new java.awt.Color(229, 93, 95));
        presidents.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton3");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(390, 60, 160, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vice-President");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 240, 30);

        jRadioButton4.setBackground(new java.awt.Color(229, 93, 95));
        vicepresidents.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("jRadioButton1");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(50, 160, 170, 23);

        jRadioButton5.setBackground(new java.awt.Color(229, 93, 95));
        vicepresidents.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("jRadioButton2");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(220, 160, 170, 23);

        jRadioButton6.setBackground(new java.awt.Color(229, 93, 95));
        vicepresidents.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("jRadioButton3");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(390, 160, 160, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("party_name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 80, 140, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("party_name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 80, 80, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("party_name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 80, 80, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("party_name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 180, 80, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("party_name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 180, 80, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("party_name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 180, 80, 14);

        jSeparator1.setForeground(new java.awt.Color(229, 93, 95));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 108, 560, 10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Senators");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 230, 240, 30);

        jSeparator2.setForeground(new java.awt.Color(229, 93, 95));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 210, 550, 10);

        jCheckBox1.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(50, 280, 130, 23);

        jCheckBox2.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("jCheckBox2");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(180, 280, 130, 20);

        jCheckBox3.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("jCheckBox3");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(310, 280, 130, 20);

        jCheckBox4.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("jCheckBox4");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(440, 280, 130, 20);

        jCheckBox5.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("jCheckBox5");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(50, 330, 130, 23);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("party_name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(200, 400, 110, 14);

        jCheckBox6.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("jCheckBox1");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(180, 330, 130, 20);

        jCheckBox7.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("jCheckBox2");
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(310, 330, 130, 20);

        jCheckBox8.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("jCheckBox3");
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(440, 330, 130, 20);

        jCheckBox9.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("jCheckBox4");
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(50, 380, 130, 23);

        jCheckBox10.setBackground(new java.awt.Color(229, 93, 95));
        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("jCheckBox5");
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(180, 380, 130, 20);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("party_name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(70, 300, 110, 14);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("party_name");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(200, 300, 110, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("party_name");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(330, 300, 110, 14);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("party_name");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(460, 300, 110, 14);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("party_name");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(70, 350, 110, 14);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("party_name");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(200, 350, 110, 14);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("party_name");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(330, 350, 110, 14);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("party_name");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(460, 350, 110, 14);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("party_name");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(70, 400, 110, 14);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 410, 70, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    void populateFields(){
        // presidents
            jRadioButton1.setText(p7.getLast_name()+", "+p7.getFirst_name());
            jLabel3.setText(p7.getParty());
            jRadioButton2.setText(p8.getLast_name()+", "+p8.getFirst_name());
            jLabel4.setText(p8.getParty());
            jRadioButton3.setText(p9.getLast_name()+", "+p9.getFirst_name());
            jLabel5.setText(p9.getParty());
            
        // vice presidents
            jRadioButton4.setText(p10.getLast_name()+", "+p10.getFirst_name());
            jLabel6.setText(p10.getParty());
            jRadioButton5.setText(p11.getLast_name()+", "+p11.getFirst_name());
            jLabel7.setText(p11.getParty());
            jRadioButton6.setText(p12.getLast_name()+", "+p12.getFirst_name());
            jLabel8.setText(p12.getParty());
            
        // senators
            jCheckBox1.setText(p13.getLast_name()+", "+p13.getFirst_name());
            jLabel14.setText(p13.getParty());
            jCheckBox2.setText(p14.getLast_name()+", "+p14.getFirst_name());
            jLabel15.setText(p14.getParty());
            jCheckBox3.setText(p15.getLast_name()+", "+p15.getFirst_name());
            jLabel16.setText(p15.getParty());
            jCheckBox4.setText(p16.getLast_name()+", "+p16.getFirst_name());
            jLabel17.setText(p16.getParty());
            jCheckBox5.setText(p17.getLast_name()+", "+p17.getFirst_name());
            jLabel18.setText(p17.getParty());
            jCheckBox6.setText(p18.getLast_name()+", "+p18.getFirst_name());
            jLabel19.setText(p18.getParty());
            jCheckBox7.setText(p19.getLast_name()+", "+p19.getFirst_name());
            jLabel20.setText(p19.getParty());
            jCheckBox8.setText(p20.getLast_name()+", "+p20.getFirst_name());
            jLabel21.setText(p20.getParty());
            jCheckBox9.setText(p21.getLast_name()+", "+p21.getFirst_name());
            jLabel22.setText(p21.getParty());
            jCheckBox10.setText(p22.getLast_name()+", "+p22.getFirst_name());
            jLabel13.setText(p22.getParty());         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voter_landing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voter_landing_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup presidents;
    private javax.swing.ButtonGroup vicepresidents;
    // End of variables declaration//GEN-END:variables
}
